### ISSUE TITLE
Confusion about the attribute named "symmetry_mapping"

### ISSUE THREAD

**Issue by chenyu-xjtu** [tum-pbs/DMCF#11]
Hi! I notice that there is an argument  named "symmetry_mapping" in class ContinuousConv, as shown in the picture. I supposed it may be used for distinguishing the ASCC and CConv, since the ASCC is implemented through CConv in the code. But I found that any use of this argument in the code is commented outhas been commented out in _convolutions.py_, so it makes me confused about the use of this attribute. 
Could you please explain the use of “symmetry_mapping”? Looking forward to your reply!!
![264977068-5186a4fd-50d3-4037-84b8-08188ef3d583](https://github.com/tum-pbs/DMCF/assets/125364727/4d7e5fdd-4055-4c47-aa98-fa45b1e03818)
![image](https://github.com/tum-pbs/DMCF/assets/125364727/e2628a7f-6f16-4c8e-a805-3b799dc4a3d2)

**Comment by Prantl** [comment]
Hi,
thanks for pointing this out! The comments were from an older version that is no longer relevant. The anti-symmetry can be activated via the "symmetric" parameter. I have adjusted the comments accordingly.
Cheers,
Lukas

**Comment by chenyu-xjtu** [comment]
Thank you for your prompt reply! Cheers!
