### ISSUE TITLE
Why not replace all the CConv with the ASCC?

### ISSUE THREAD

**Issue by chenyu-xjtu** [tum-pbs/DMCF#14]
Hi! It seems that the ASCC is the enhanced version of the CConv. Why not replace all the CConv with the ASCC to better conserve momentum? Actually I have tried this but the performance deteriorated instead. Is there any reasonable explanation? Thanks!

**Comment by Prantl** [comment]
Hi, this is because the antisymmetry introduces a strong constraint. This makes the problem much harder for the network to solve. Even with the ASCC only at the end, it was very difficult to tune the network to achieve the current state. In return, the network generalizes much better.

**Comment by Prantl** [comment]
The paper has a short paragraph with an example (Standing Liquid) in the Result section, which briefly discusses this.
