### ISSUE TITLE
Question about the max density?

### ISSUE THREAD

**Issue by chenyu-xjtu** [tum-pbs/DMCF#15]
Hi! I am confused with the metric "Max Density". Does the metric "Max Density" refer to the maximum density of fluid particles, or is it the relative error between the maximum density of the fluid and the maximum density of the ground truth?

In the paper, Formula (15) for "Max Density" likely denotes the latter, i.e., the relative error of maximum density, where a value closer to 0 is preferable. 
![image](https://github.com/tum-pbs/DMCF/assets/125364727/9e1706d2-a78c-4659-8ea2-04a3ccd58403)

However, Table 2 in the appendix suggests that "Max Density" is the former, meaning the maximum density of fluid particles, where values closer to 1 are considered better.
![image](https://github.com/tum-pbs/DMCF/assets/125364727/ddacf1e3-ed04-4b63-8c13-e3576496ead5)

Looking forward to your early reply! Thanks!

**Comment by Prantl** [comment]
Hi! Yes I can see why this can be confusing.
The latter is true. The values in Table 2 are not the raw error values but relative accuracy values as described in Figure 6. I.e. a value of 1 corresponds to the error of our final method, while small values represent a lower relative accuracy and thus larger error. A value of 0.5, for example, would mean half the accuracy and double the error. We chose this format to relate the error to the final method, which we felt was important in an ablation study, and to normalise the error evaluation for better visualisation in the graph. I hope that answers your question?
