### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by Science2AI-TaoXu** [tum-pbs/DMCF#16]
python 3.9
tensorflow==2.5.0
open3d==0.15.2
when I try to use Pretrained Models as:
python run_pipeline.py --cfg_file configs/WBC-SPH.yml \
                       --dataset_path AI4CFD/WaterRamps \
                       --ckpt_path checkpoints/WBC-SPH \
                       --split test
                       
the error is :
File "/home/taoxu/test02/miniconda3-taoxu/envs/dmcf2/lib/python3.9/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/taoxu/test02/taoxu/088-3D/DMCF/utils/tools/sampling_so.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb

**Comment by Prantl** [comment]
Hi!

It looks like the custom TF operators are not being found. We use custom TF modules in some scenarios that have to be built manually. Did you do that? It is described in the "Optional" part of the "Dependencies and Setup" chapter:

Build FPS/EMD module: ```cd utils; make; cd ..```
