### ISSUE TITLE
May I ask how you used splishsplash to generate a dataset and put it in a format that the network could use?

### ISSUE THREAD

**Issue by Vesuvius6** [tum-pbs/DMCF#7]
May I ask how you used splishsplash to generate a dataset and put it in a format that the network could use?

**Comment by Prantl** [comment]
The data was generated basing on the code of previous work (https://github.com/isl-org/DeepLagrangianFluids). The required code is in the 'datasets' folder. 'create_data.sh' is the shell script to run the data generation.

**Comment by Vesuvius6** [comment]
Thank you very much. I am very glad to read your reply. :-) I will try to generate some custom examples.
