### ISSUE TITLE
Hi,How to run a 3D pipeline ?

### ISSUE THREAD

**Issue by yyf0202** [tum-pbs/DMCF#8]

**Comment by Prantl** [comment]
Hi,

you can run other pipelines using the corresponding config file (folder "config"). To run the 3D pipeline, you could use for example the following command:

```
python run_pipeline.py --cfg_file configs/Liquid3d.yml \
                       --dataset_path PATH/TO/DATASET \
                       --ckpt_path checkpoints/Liquid3d/ckpt \
                       --split test
```

In the section "Datasets" there is a description of how to get the corresponding dataset.

I hope that answers your question.

Best regards,
Lukas
